version: '3.8'

volumes:
    postgres_data:
        driver: local
    traefix_data:
        driver: local

services:
    postgres:
        image: postgres:13.3-buster
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        # restart: 'always'
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: P@sswOrd!
            #POSTGRES_HOST: postgres
    traefik:
        image: traefik:v2.4.8
        container_name: traefik
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - 80:80
            - 3000:8080
    keycloak:
        image: jboss/keycloak:latest
        container_name: keycloak
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_PORT: 5432
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_SCHEMA: public
            DB_PASSWORD: P@sswOrd!
            KEYCLOAK_USER: keycloak
            KEYCLOAK_PASSWORD: Pa55w0rd
            JAVA_OPTS: "-server -Xms64m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true   --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -Djboss.tx.node.id=keycloak21"
#            JAVA_OPTS: jboss.tx.node.id=keycload01
            #- "JAVA_OPTS=-Djboss.tx.node.id=keycload01"
            # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
            #JDBC_PARAMS: "ssl=true"
            # KEYCLOAK_LOGLEVEL: DEBUG
            # JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
            # JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
        ports:
            - 8080:8080
            - 9990:9990
            - 8443:8443
        depends_on:
            - postgres
        labels:
            traefik.enable: true
            traefik.port: 8080
            traefik.protocol: http
            traefik.frontend.rule: Host:localhost
            traefik.frontend.passHostHeader: true
            # traefik.backend.loadbalancer.stickiness: true